### ISSUE TITLE
Missing navigation path items for navigation properties with contains target

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#123]
The current beta description is missing a path item and corresponding operations for

`/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{reply_id}/hostedContents`

Where:
- Hosted contents is a navigation property on chatMessage (no contains target)
- Replies is a collection of chatMessages navigation property on chatMessage (contains target true)
- Messages is a collection of chatMessages navigation property on channel (contains target true)
- Channels is a collection of channel navigation property on team (contains target true)
- And Teams is a collection of teams

**Comment by irvinesunday** [comment]
From the `chatMessage` Entity type snippet below:

![image](https://user-images.githubusercontent.com/40403681/142479580-fb1dd8e2-2353-4db7-8092-5eeda69f8407.png)

`hostedContents` navigation property should be accessible using the path:

`/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/hostedContents`

or to retrieve a single entity...

`/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}`

The `replies` navigation property can be accessible using the path: 

`/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies`

or to retrieve a single entity...

`/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}`

Expansion beyond the `.../replies/{chatMessage-id1}` path is not possible despite the containment, because the defining entity type (`graph.chatMessage`) references the same entity type (`chatMessage`) that the `replies` navigation property is contained in, and this will lead to circular references.

**Comment by baywet** [comment]
Thanks for the additional information.
The expansion logic could detect circular references effectively

- not expanding /teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{reply_id}/replies, as it's already "been through" the replies navigation property
- expanding all the way to /teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{reply_id}/hostedContents

Instead of relying on a blanket behavior of not expanding any navigation property beyond a certain point.

**Comment by darrelmiller** [comment]
The problem is that replies should not be contained.  Replies are also messages and therefore their canonical path is via the messages collection.  I'll go confirm this with Anand.

**Comment by darrelmiller** [comment]
It appears I may be wrong here.  It looks like you cannot access any message in a channel via ./channel/messages.  Replies are actually contained in the root chat message. Sigh.

**Comment by baywet** [comment]
and this appears to be deployed to v1.0 now, so turning around will be difficult...
https://docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&tabs=http

Hence my earlier comment on the expansion logic which should evaluate whether it's already been here on a navigation property by navigation property base and not on an entity base.
