### ISSUE TITLE
Generated types should resolve to the same type when they are navigation properties

### ISSUE THREAD

**Issue by sebastienlevert** [microsoft/OpenAPI.NET.OData#150]
This is the start of a discussion that can unlock unlimited potential to build extensibility on top of some of our SDKs generated using the OData library.

When looking at building extensibility on top of our SDK, I am expecting to be able to add extension methods on the `RequestBuilder` to allow it to do what I want. Now, from what I understand, when an SDK is generated via CSDL to OpenAPI, we are losing this information and Kiota, for instance, is generating multiple types with the same structure. 

In a Graph world, think about the following : 

.Me should be the same as .Users["id"], which is not. So if I want to add an extension method to .Me, I need to add it to multiple RequestBuilder, making devs life harder and they need to understand fully the API.

I would love to be able to do the following : 

client.Me.Colleagues.Get() and this should also work with client.Users["id"].Colleagues.Get()

Adding @vbiret to this conversation.

**Comment by baywet** [comment]
To add some context to the discussion, when generating from OData we know that /me and /users/{id} are the same exact thing (set of endpoints under those paths is the same) because of the way OData conventions work.
We kind of lose that information when working with OpenAPI after the conversion process goes through the metadata as it creates separate path items, and there's no way to tell they are the same.
If the conversion process could add some kind of extension we could read in to know "oh yeah, that path and under are the same as this other one", Kiota could greatly reduce code duplication.

@darrelmiller to provider his insights on that.

**Comment by darrelmiller** [comment]
`/me` and `/users/{id}` are not the same thing, even in OData.  You can apply capability annotations to one that do not exist on the other.  Also, the only case that is the same is where the {id} is equal to the signed in user.  The path '/users/{id}' requires different scopes than '/me'.  

I understand the appeal of trying to re-use the entity model that exists conceptually in CSDL, but the reality of the actual API implementation rarely actually means that the two paths have the same characteristics.

**Comment by sebastienlevert** [comment]
Fair enough. If models are the same, I think we can work with this, considering we wouldn't use extension methods to really fully extend, but using the Task construct to accomplish the same. We would decouple ourselves from the `RequestBuilder;  and would not run into this issue.

**Comment by baywet** [comment]
yeah models are deduped except for collection responses but this is tracked with #125.
Closing.
