### ISSUE TITLE
Add support for Graph AGS extensions

### ISSUE THREAD

**Issue by adhiambovivian** [microsoft/OpenAPI.NET.OData#192]
Add capability to parse and surface AGS extensions that will help with accessing & exposing hidden properties on AGS such as 'isHidden' which are mainly captured on the CSDL today.

**Comment by irvinesunday** [comment]
Discussion needed as a previous attempt to implement reading custom attributes was debated inconclusively. See the discussion on this PR https://github.com/microsoft/OpenAPI.NET.OData/pull/152

**Comment by darrelmiller** [comment]
The previous attempt to use custom attributes was disbanded because we identified an equivalent OData annotation that that did what we needed.

In this case we have a set of annotations that there are no equivalent OData annotations and as they are implementation specific, there is no design to add standardized capabilities.

In order to support these annotations I propose adding a config setting that accepts a dictionary that maps a qualified XML attribute name to a corresponding OpenAPI x- extension.  When converting the document from CSDL to OpenAPI, we should check on each element if any of the present direct annotations has a corresponding mapping to an OpenAPI x- extension.  If it does, then the extension should be output.  If there are no mappings provided then no extensions will be created.

This will make the feature completely opt-in and only the annotations that are of interest should be translated.  Xml Attributes can only have primitive values, so they should map simply to OpenAPI primitive values.

**Comment by irvinesunday** [comment]
In which OpenAPI object will these extensions be inserted into? `OpenAPIOperation.Extensions`?

**Comment by darrelmiller** [comment]
We are going to have to try and attach the annotation to the closed natural equivalent in OpenAPI.

An attribute (e.g. isHidden) on a navigation property would probably map to an extension on OpenApiPathItem.
An attribute (e.g. isHidden) on structural property would map to a OpenApiSchema

**Comment by irvinesunday** [comment]
@darrelmiller can an element have more than 1 custom XML attribute?
