### ISSUE TITLE
New $count endpoints in OpenAPI missing parameters

### ISSUE THREAD

**Issue by calebkiage** [microsoft/OpenAPI.NET.OData#207]
*Short summary (3-5 sentences) describing the issue.*
Some endpoint paths e.g. `/users` require the `ConsistencyLevel` header defined. This is shown by having the header added in the operation parameters as shown below:
![image](https://user-images.githubusercontent.com/747955/162030212-e363f854-618e-4fa8-97dd-7e1951b3f566.png)
The new $count endpoints e.g. `/users/$count` don't have the parameters defined in the OpenAPI schema file:
![image](https://user-images.githubusercontent.com/747955/162030506-1f147b38-75ea-45ce-bd94-33f810076b6c.png)

### Assemblies affected

*Which assemblies and versions are known to be affected?*
Unknown, but the [openapi file](https://github.com/microsoftgraph/msgraph-metadata/blob/e7568c69f05d2955e127c04358f59988e1072203/openapi/v1.0/openapi.yaml) generated in commit microsoftgraph/msgraph-metadata@e7568c69 is affected

### Steps to reproduce

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result

*What would happen if there wasn't a bug.*
The $count endpoints should list the required headers like `ConsistencyLevel` in the schema

### Actual result

*What is actually happening.*
There is no header parameter in the schema

### Additional detail

*Optional, details of the root cause if known.

**Comment by baywet** [comment]
considering the entity set has an annotation to indicate the header is present, it should propagate to the raw count endpoint.

now the question is: should it propagate to OData type cast path segments as well? navigation properties? the index endpoint `users/id` ? If so for which operations? ping @darrelmiller to bring clarity on this.

```xml
<Annotations Target="microsoft.graph.GraphService/directoryObjects">
        <Annotation Term="Org.OData.Capabilities.V1.ReadRestrictions">
          <Record>
            <PropertyValue Property="CustomHeaders">
              <Collection>
                <Record>
                  <PropertyValue Property="Name" String="ConsistencyLevel" />
                  <PropertyValue Property="Description" String="Indicates the requested consistency level." />
                  <PropertyValue Property="DocumentationURL" String="https://developer.microsoft.com/en-us/office/blogs/microsoft-graph-advanced-queries-for-directory-objects-are-now-generally-available/" />
                  <PropertyValue Property="Required" Bool="false" />
                  <PropertyValue Property="ExampleValues">
                    <Collection>
                      <Record>
                        <PropertyValue Property="Value" String="eventual" />
                        <PropertyValue Property="Description" String="$search and $count queries require the client to set the ConsistencyLevel HTTP header to 'eventual'." />
                      </Record>
                    </Collection>
                  </PropertyValue>
                </Record>
              </Collection>
            </PropertyValue>
          </Record>
        </Annotation>
      </Annotations>
```

**Comment by darrelmiller** [comment]
Currently AGS strips off the ReadRestrictions that are added by the workload team and we add them back manually in the XSLT.  The Identity Graph team are currently implementing a mechanism to allow us to access the unfiltered metadata which will give us all of these annotations without us having to manually add them back.  We should wait until this work is done, rather than updating the XSLT.

**Comment by baywet** [comment]
and to clarify, we shouldn't either propagate that information automatically?

**Comment by peombwa** [comment]
Reviving this as it affects https://github.com/microsoftgraph/msgraph-metadata/issues/185.

To @baywet's question, should we propagate the header to OData type cast path segments, navigation properties, and index endpoint? I would say yes since this is how the the header is used. See [AAD advanced queries](https://docs.microsoft.com/en-us/graph/aad-advanced-queries?context=graph%2Fapi%2Fbeta&view=graph-rest-beta&tabs=http). I have a branch in the [metadata repo](https://github.com/microsoftgraph/msgraph-metadata/blob/po/consistencyLevelImprovements/transforms/csdl/preprocess_csdl.xsl#L762-L999) that adds the header to supported navigation properties via XSLT. The supported navigation properties are extracted from [AAD advanced queries](https://docs.microsoft.com/en-us/graph/aad-advanced-queries?context=graph%2Fapi%2Fbeta&view=graph-rest-beta&tabs=http).

@darrelmiller, the [metadata with ReadRestrictions](https://github.com/microsoftgraph/msgraph-metadata/blob/master/schemas/beta-Prod.csdl) from AGS does not currently have the header applied to supported navigation properties. This will need to be added by the workload to fix https://github.com/microsoftgraph/msgraph-metadata/issues/185 if we are to use AGS's metadata.

**Comment by baywet** [comment]
Thanks. But then the propagation should be limited to get opérations, correct?

**Comment by baywet** [comment]
@timayabi2020 what's the rationale behind closing this?

**Comment by timayabi2020** [comment]
@baywet apologies I might have closed it by mistake from the powershell project board.
