### ISSUE TITLE
Missing Query Parameters in Channel messages

### ISSUE THREAD

**Issue by timayabi2020** [microsoft/OpenAPI.NET.OData#250]
While calling the Get channel messages delta service via powershell command ```Get-MgTeamChannelMessageDelta -TeamId <team-id> -ChannelId <channel-id> -Skiptoken <token-id>```, an error is shown "A parameter cannot be found that matches parameter name 'Skiptoken".
The Teams.yml file that we pull from openApi is missing skiptoken and delta token as described [here](https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&tabs=powershell)

<img width="973" alt="image" src="https://user-images.githubusercontent.com/10947120/178988684-df4da758-a7ea-4500-9ef1-a37ec8d26fd7.png">

**Comment by irvinesunday** [comment]
According to the [docs](http://docs.oasis-open.org/odata/odata/v4.0/os/part1-protocol/odata-v4.0-os-part1-protocol.html#_Toc372793701)...
![image](https://user-images.githubusercontent.com/40403681/185762053-f0354482-4e28-4afd-8747-175f6721b068.png)

the `$skiptoken` is used for server-side paging and not for constructing requests. The parameters object contains parameters that are used for constructing the request. 
Both `$deltatoken` and `$skiptoken` are returned by the service after the first call. These should not be defined in the list of parameters for a given path.

cc: @darrelmiller / @baywet

**Comment by timayabi2020** [comment]
@irvinesunday thanks for the clarification. After further analysis I realized that the SDK snippet examples as documented on docs are assuming that the skip token is a query parameter. Ideally, skip parameter is supposed to be abstracted from the customer when a request with pagination argument e.g ``-Top 5`` is made. Workload provides http examples only on how to do pagination and api doctor scraps through that to generate the other language specific examples.
Eventually generated examples end up confusing the snippet generator on Devx. I will open an issue on devx to have generation of such snippets skipped since they also affect raptor passrates.

**Comment by andrueastman** [comment]
Given that that a `$skiptoken` or `$deltatoken` can be valid for[ several days](https://docs.microsoft.com/en-us/graph/delta-query-overview#token-duration), I think there might be a use case where a user who is doing a delta sync once every day (or week?) may choose to extract/store the `$skiptoken` or `$deltatoken` in order to use it as a query parameter for the next request rather than storing the entire URL for use in the next sync. 

Not providing the `$skiptoken` or `$deltatoken` in the metadata would complicate this scenario as the metadata would "technically" not be giving a true picture of what the given API is capable of. (This is from the perspective that Kiota generated SDKs expect query parameters to reflect the metadata and not really allow custom query parameters).

Thoughts?

**Comment by timayabi2020** [comment]
cc @peombwa

**Comment by baywet** [comment]
They are not supposed to store just the skip or delta token but the whole link instead.
