### ISSUE TITLE
workbook property on driveItem is never getting expanded

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#327]
The workbook property on the driveItem entity is never getting expanded, even on the canonical path of /drives/{id}/items/{id}/

### Assemblies affected

1.2.0-preview8

### Steps to reproduce

If you search for /workbook/ in https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml you won't find any entry.

### Expected result

/workbook/ and sub nodes to be present under driveItem's canonical path.

### Actual result

*What is actually happening.*

### Additional detail

*Optional, details of the root cause if known.

**Comment by darrelmiller** [comment]
We can only afford to expand this property once. If we can confirm that contained navigation properties on driveItem only get expanded under `/drives/{driveId}/item/{itemId} then we can remove the workbooks entityset.  Otherwise we cannot afford to as it will explode the generated OpenAPI with multiple copies of the Excel API.

**Comment by baywet** [comment]
after going down the rabbit hole with Darrel it appears that the conversion it doing the right thing, the metadata is wrong, we'll follow up with a new issue there.
