### ISSUE TITLE
add a setting to avoid adding the namespace to method segments

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#335]
The current conversion systematically adds the namespace of the method to the path segment.
While it might be desired in some contexts, most of the time it only makes URIs (and namespacing in code gen) longer.

I'm suggesting to add a convert setting to go from this for actions and functions
```
.../me/microsoft.graph.foo()
````

to that

```
.../me/foo()
```

The setting name would be something like "AppenNamespaceToMethodPathSegment` default true. When true the behaviour would stay the same as now, when false it'd be the new one.

**Comment by baywet** [comment]
actually @irvinesunday please hold any work on that. Looking into this week's generation result we have excel count functions conflicting with raw $count endpoints.
Assuming we leave the prefixes in place, and that we merge the kiota fix I linked, we'd get any method prefixed, which would solve the conflict. The only drawback is that it'd make for an uglier dev experience (`client.Me.Drive.Item["foo"].Workbook.Worksheet["bar"].Tables.MicrosoftGraphCount.GetAsync()` for the OData function)

**Comment by irvinesunday** [comment]
> actually @irvinesunday please hold any work on that. Looking into this week's generation result we have excel count functions conflicting with raw $count endpoints. Assuming we leave the prefixes in place, and that we merge the kiota fix I linked, we'd get any method prefixed, which would solve the conflict. The only drawback is that it'd make for an uglier dev experience (`client.Me.Drive.Item["foo"].Workbook.Worksheet["bar"].Tables.MicrosoftGraphCount.GetAsync()` for the OData function)

Noted!

**Comment by andrueastman** [comment]
Hey @baywet, 
The `MicrosoftGraphCount` segment makes for a not-so-great dev experience which may not be worth it for the sake of what can be considered as an edge case. 

Would it be possible to let this go on and detect duplicate segments after sanitization and try to disambiguate them from Kiota. From this library's perspective `'/drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/columns/count()'` and
`'/drives/{drive-id}/items/{driveItem-id}/workbook/tables/{workbookTable-id}/columns/$count'` would still be two unique paths and technically the collision is caused by Kiota sanitizing the segment as https://github.com/microsoft/kiota/issues/2234 also needs to be fixed.

**Comment by baywet** [comment]
Thanks for reverting on this. I agree, the more I think about it, the more I think the fix lies within Kiota and not here.
With microsoft/kiota#2213 we've made a step in the right direction, but I missed one thing as you outline in microsoft/kiota#2234.
What will be left to fix after that is when path segments only differ in special characters, this one will be interesting as kiota is not parsing the tree in a deterministic reason for performance reasons. But that's probably an edge case of an edge case that can be sorted out when we get feedback about that.
Closing this here. No changes required for the conversion library. Thanks everyone.
