### ISSUE TITLE
Duplicate paths causes failed transformed metadata

### ISSUE THREAD

**Issue by andrueastman** [microsoft/OpenAPI.NET.OData#343]
At the moment, Hidi fails to generate the latest beta openApi file for Microsoft graph with the following error

```shell
Tool 'microsoft.openapi.hidi' (version '1.2.2') was successfully installed.
crit: Microsoft.OpenApi.Hidi.OpenApiService[0]
      Could not transform the document, reason: An item with the same key has already been added. Key: /administrativeUnits/microsoft.graph.delta()
```
Reference https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=106293&view=logs&j=4c81e8e4-6eb9-5def-7261-b44ad0fc1b7d&t=163839c6-f69e-5b5d-39e2-5b38e97d3fe3

Digging further into this it looks like the latest metadata has introduced the delta function to the directoryObjectt ype which is the base type of `administrativeUnit`

```xml
      <Function Name="delta" IsBound="true">
        <Parameter Name="bindingParameter" Type="Collection(graph.directoryObject)" />
        <ReturnType Type="Collection(graph.directoryObject)" />
      </Function>
```
Due to the check done here to try to apply bound functions on all the derived types of the object, two paths are generated due to the already existing function on the base type and existing function on the actual type. 

https://github.com/microsoft/OpenAPI.NET.OData/blob/6e6442946e21c597078de3b25ab85290d6d7db63/src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs#L668

This causes the generation to fail due to the duplicated keys when trying to build the dictionary of paths at 
https://github.com/microsoft/OpenAPI.NET.OData/blob/master/src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiPathItemGenerator.cs#L58

Notes
- Is it incorrect to have a bound function on a base type redeclared on the child type? (This would mean that the metadata is incorrect)
- We should probably try to use `Dictionary.TryAdd` and maybe log a warning in the event that we find duplicate paths to prevent failures
- Paths generated from derived types could append a suffix to ensure their uniqueness to if the metadata is valid. 

cc @irvinesunday @baywet

**Comment by baywet** [comment]
happy that we came to the same conclusions, [for reference](https://github.com/microsoftgraph/msgraph-metadata/issues/276).
I don't think it's valid from an OData perspective to defined the same function on a base and on a derived type. While using try add would make the conversion process more resilient, I believe the metadata itself should be fixed.

**Comment by irvinesunday** [comment]
I asked our good friend ChatGPT that question, and here was the response:

"In OData conventions, it is valid to declare a function on a base type and the same function on the base type's derived type. This is because OData supports inheritance, which means that a derived type can inherit properties, functions, and other elements from its base type.

When you declare a function on a base type, it becomes available to all derived types. However, you can also declare the same function on a derived type, which would allow you to override the behavior of the function in the base type. This is a common programming practice in object-oriented programming and is supported by OData.

For example, consider a base type called "Person" with a function called "GetFullName". You could then define a derived type called "Employee" that inherits from the Person type, and also define a function called "GetFullName" on the Employee type. This would allow you to customize the behavior of the GetFullName function specifically for the Employee type, while still allowing the function to be used by instances of both the Person and Employee types.

Overall, while it is valid to declare a function on a base type and the same function on the base type's derived type in OData conventions, you should carefully consider the behavior you want to achieve and the potential impact on your data model before doing so."


I also picked this from the [spec.](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_Functionoverloadresolution)

![image](https://user-images.githubusercontent.com/40403681/220432076-c4e93745-5cf3-4e95-961b-c3cb101a7b47.png)

**Comment by baywet** [comment]
Lord help us if we start trusting the bots 🤣

So the complete fix here would be 
1. try add, 
2. when false, check whether the thing that's already present is a function on a base type
3. if yes, remove it, and add a segment for the current function (in case parameters changed, etc...)
4. if no, log a warning

Does that make sense to everyone?

**Comment by irvinesunday** [comment]
> Lord help us if we start trusting the bots 🤣
> 
> So the complete fix here would be
> 
> 1. try add,
> 2. when false, check whether the thing that's already present is a function on a base type
> 3. if yes, remove it, and add a segment for the current function (in case parameters changed, etc...)
> 4. if no, log a warning
> 
> Does that make sense to everyone?

Seeking clarification. 

In your suggestion...

1.  `pathItems.TryAdd()` (for example) `/administrativeUnits/microsoft.graph.delta()`.
2. When false, we check whether the delta function is a base type function?
3. If it is a base type function...? the next part isn't as clear.
4. If it is not a base type function, log a warning?

**Comment by baywet** [comment]
1. pathItems.TryAdd() (for example) /administrativeUnits/microsoft.graph.delta().
2. if 1. was true, do nothing, else check whether the existing delta segment a function that is bound to one of the base types of administrative units? (directory object, entity...)
3. if 2 is true, remove the segment that's already here and add the new segment based on the function that's bound to the current type else log a warning
4. there's no step 4

Does that clarify things?

**Comment by andrueastman** [comment]
> 1. pathItems.TryAdd() (for example) /administrativeUnits/microsoft.graph.delta().
> 2. if 1. was true, do nothing, else check whether the existing delta segment a function that is bound to one of the base types of administrative units? (directory object, entity...)
> 3. if 2 is true, remove the segment that's already here and add the new segment based on the function that's bound to the current type else log a warning
> 4. there's no step 4
> 
> Does that clarify things?

+1

**Comment by irvinesunday** [comment]
> 1. pathItems.TryAdd() (for example) /administrativeUnits/microsoft.graph.delta().
> 2. if 1. was true, do nothing, else check whether the existing delta segment a function that is bound to one of the base types of administrative units? (directory object, entity...)
> 3. if 2 is true, remove the segment that's already here and add the new segment based on the function that's bound to the current type else log a warning
> 4. there's no step 4
> 
> Does that clarify things?

Mine is a somewhat similar flow but with a different POV. Since the `pathItems` dictionary keys are string, we cannot infer any information about the operation's binding parameter properties from this. We can only deduce this information from the _new path_ object that is trying to be added. My updated flow would be:

1. `TryAdd()` path
2. If false AND last segment is NOT an operation segment, log an error (don't add the path)
3. Otherwise (true), check whether the entity type of the binding parameter of the operation of the _'new path'_ to be added has derived types.
   - If false (this is a function bound to a derived type and what was added before was a function bound to a base type), update the existing path in dictionary with the incoming path item.
   - Otherwise (true), check whether the entity bound by this operation (the second last segment) is contained in the list of derived types?
     - If true, skip (don't add the path, a function bound to a derived type was added before)
     - If false, log an error and skip (don't add the path)
