### ISSUE TITLE
Duplicate operation Ids (Currently blocking Microsoft Graph SDK PowerShell releases)

### ISSUE THREAD

**Issue by timayabi2020** [microsoft/OpenAPI.NET.OData#604]
Running the weekly open Api refresh pipeline updates the [sliced Open Api files](https://github.com/microsoftgraph/msgraph-sdk-powershell/tree/dev/openApiDocs) in PowerShell with duplicate operation Ids causing AutoREST build failures.

This is an example of a call made to DevX API to slice the larger Open API file to small files based on tags passed to the service.
https://devxapi-func-prod-eastus.azurewebsites.net/$openapi?tags=^users.calendar$&title=Calendar&openapiversion=3&style=Powershell&fileName=powershell_v2&graphVersion=v1.0&singularizeOperationIds=true
If you execute a ``GET`` request and search for ``user.calendar.calendarView.instance_ListExtension``, you will see that the operation Id has been assigned to two different paths.

![Image](https://github.com/user-attachments/assets/f5f98ccb-37fe-439a-b426-979dba8bcd2b)

Attached is a file showing all the duplicated operation Ids for v1.0 paths.
[duplicateOperationIds.csv](https://github.com/user-attachments/files/17729500/duplicateOperationIds.csv)

**Comment by timayabi2020** [comment]
When the refresh runs, there is a ``ForceRefresh`` query parameter passed to DevX and my expectation is that no stale data will be downloaded. Is there something else that needs to be done to ensure freshness of data?

**Comment by andrueastman** [comment]
@timayabi2020 @irvinesunday @Ndiritu 

To summarize our earlier discussion, the conversion library is not to blame for the duplicate operation ids in the document. 
This is also validated at PR level in the metadata repo using the check added at the link below.
https://github.com/microsoftgraph/msgraph-metadata/blob/350c13155dbf986baee9b9664357e343a4059abf/.github/workflows/openapi-parser-validation.yml#L41

The issue causing the duplicate Id is the singularization logic in devX api which we discovered due to updated groupings of paths( paths for functions/actions moved to other files making the bug apparent) due to the issue at https://github.com/microsoft/OpenAPI.NET.OData/issues/605. 

For now we can close this specific issue(regarding duplicate operation ids) as it is not an issue with the library and follow it up on devXApi via https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/2255

I'll also provide more details on the tags grouping issue at https://github.com/microsoft/OpenAPI.NET.OData/issues/605
